### ISSUE TITLE
[es] update needed

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-plan-policies-overview#15]
Hi @cmuncharaz

We will be promoting translations the week of 17 May, along with Global Accessibility Awareness Day (GAAD).

Would you be able to update this translation? Or, should we ask someone else to update it?

https://raw.githubusercontent.com/w3c/wai-plan-policies-overview/master/content/index.es.md

I added the new text in English:
* 2 paragraphs in the footer (which is near the top of the file :-)
* section with video and transcript

We have someone translating the subtitle file -- which is the same as the first column in the table. So you could use that when it's done. :-) Let me know what questions you have.

**Comment by cmuncharaz** [comment]
Text translated. Awaiting subtitles to translate table.

**Comment by cmuncharaz** [comment]
@shawna-slh:

Please, let me know how to access the translated subtitle file in order to use it in the table. Thank you!

**Comment by shawna-slh** [comment]
Unfortunately we do not have it yet. You can leave that untranslated for now. Or do the translation yourself. Whichever you prefer.

**Comment by cmuncharaz** [comment]
@shawna-slh:

Translated the table. Please, let me know when the subtitle file is available in case we need to make sure both versions match.

Pull request: https://github.com/w3c/wai-plan-policies-overview/pull/18

**Comment by shawna-slh** [comment]
>Translated the table. 

Thanks!

> Please, let me know when the subtitle file is available in case we need to make sure both versions match.

I will connect you via e-mail.
