### ISSUE TITLE
Malformed <p> tag

### ISSUE THREAD

**Issue by cmuncharaz** [w3c/wai-plan-policies-overview#17]
Notice that the end `<p>` tag in the first footer paragraph on video description is missing the closing angle bracket:

`<p>Note about video description: The video on this page does not include synchronized audio description because the visuals only illustrate the audio and do not provide additional information. In this case, audio description would be more distracting than useful to most people, including people who cannot see the visuals. Description of visual information is integrated in the Text Transcript with Description of Visuals (“descriptive transcript”).</p`

**Comment by remibetin** [comment]
Thanks @cmuncharaz for raising this issue! It is fixed by https://github.com/w3c/wai-plan-policies-overview/pull/29
